# config.yaml

paths:
  root: C:/github/Tree-Canopy-Detection
  data: src/data

  train_images: src/data/train_images
  train_images_zip: src/data/train_images.zip
  train_masks: src/data/train_masks

  eval_images: src/data/evaluation_images
  eval_images_zip: src/data/evaluation_images.zip
  eval_masks: src/data/eval_masks

  models: models
  notebooks: notebooks

  checkpoint: "checkpoints/unet_resnet34_best.pth"
  best_model: "checkpoints/best.pth"

  label_encoder: "checkpoints/le.pickle"
  plots: "checkpoints/plots"


weights:
  labels: 1.0
  bbox: 1.0
  
params:
  image_size: 512
  num_workers: 0
  seed: 42

  # model params
  encoder_name: resnet34
  encoder_weights: imagenet
  in_channels: 3
  classes: 1

  # training params
  batch_size: 8
  epochs: 10
  learning_rate: 1e-4
  best_val_loss: 1.0e9
  early_stop_patience: 5

  # scheduler
  scheduler_factor: 0.5
  scheduler_patience: 3
  scheduler_verbose: True

