# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CAP6415_F25_project-Tree-Canopy-Detection',
                'doc_host': 'https://bluefate.github.io',
                'git_url': 'https://github.com/bluefate/CAP6415_F25_project-Tree-Canopy-Detection',
                'lib_path': 'src'},
  'syms': {'src.core': {'src.core.foo': ('core.html#foo', 'src/core.py')}, 'src.utils.config': {}, 'src.utils.helpers': {}}}
